数据库控制文件是数据库启动和操作成功所必需的很小的二进制文件。控制文件是由oracle数据库在数据库操作中持续更新的，所以它必须在数据库打开的时候保持可用可写的状态，如果控制文件因为其他原因不能存取，那么数据库就无法正常运作。

== 控制文件的作用

控制文件是oracle数据库用来寻找数据库文件和正常管理数据库状态的重要文件。控制文件包括如下信息：

* 数据库名和数据库唯一标识（DBID）
* 数据库创建的时间戳
* 数据文件、联机重做日志文件和归档重做日志文件的信息。
* 表空间信息
* RMAN 备份

控制文件有如下几个用途：

* 它包含了启动数据库时所需的关于数据文件、在线重做日志文件等等的信息
+
控制文件追踪了对数据库的结构性更改，例如每次有数据文件或者重做日志被增加、重命名或从数据库中删除，控制文件都会及时更新来反映这种物理结构的变化。

* 它包含了在数据库未打开时必须能够访问的元信息
+
例如，控制文件包含了恢复数据库所需的信息，包括检查点。检查点能够告诉我们实例恢复要从重做日志流中的哪个SCN开始。在检查点SCN之前所做的更改都确保已经保存到数据文件中了。每隔至少3秒，检查点进程会在控制文件中记录重做日志中检查点的位置信息。

Oracle 数据库在数据库使用过程中会持续的读取和写入控制文件。例如，恢复数据库涉及到从控制文件中读取所有的数据文件的名字。其它操作，如添加数据文件，会更新控制文件中已保存的信息。

== 多控制文件

像重做日志文件一样，oracle数据库使用多个相同的控制文件，它们同时为一个数据库打开。通过在不同磁盘上为单个数据库储存多个控制文件，可以预防与控制文件相关的单点故障。

如果包含一个控制文件的单个磁盘挂掉，那么当前的实例在oracle数据库试图读取损坏的控制文件时就会失败。但只要在其他磁盘上还有当前控制文件的拷贝，那么当前实例就可以无须恢复就重新启动。
如果在操作过程中数据库的所有控制文件都永久性的丢失了，那么实例会被终止，并且需要进行媒体恢复。由于当前的拷贝已经不可用，所以要使用控制文件的老的备份。

== 控制文件的结构

关于数据库的信息存储在控制文件中不同部分。每个部分都是一系列关于数据库某个方面的记录。例如，控制文件中的一部分跟踪着数据文件，包含了一系列记录，每条对以一个数据文件。每个部分都被存储在多个逻辑控制文件块里。记录可以在一个部分内跨块。

控制文件包含了以下类型的记录：

*	循环的重用记录
+
这些记录包含一些非核心的信息，它们在需要时会被覆盖。当所有记录都写满后，数据库要么扩展控制文件来为新记录制造空间，要么覆盖最旧的记录。例如归档重做日志和RMAN备份。

*	非循环的重用记录
+
这些记录包含了核心的信息，它们不会经常变化并且不能被覆盖。例如表空间、数据文件、联机重做日志文件以及重做线程的信息。Oracle数据库从不重用这些记录，除非相应的对象从表空间中删除。

可以查询动态性能视图，也叫V$视图，来查看存储在控制文件中信息。例如，可以查询V$DATABASE来获取数据库名和DBID。但是只有数据库可以更改控制文件中的信息。

读写控制文件块和读写数据文件块不同。Oracle数据库读写控制文件时，直接从磁盘中读写到PGA中。每个进程都分配了一定数量的PGA内存给控制文件块。
